version: "3"
services:
  machaonweb:
    build: .
    volumes:
      - YOUR_CERTS_PATH_ROOT:/etc/machaon_certs
      - YOUR_DATA_PATH_ROOT:/opt/storage 
    environment:
      - DATABASE_URL=mysql://DBUSER:DBPASSWORD@DBIP:DBPORT/machaon
      - CORS_URL1=http://localhost:3000
      - CORS_URL2=http://localhost:3000
      - CAPTCHA_SECRET=YOUR_SECRET_API_KEY
      - MTLS_CERTS_PATH=YOUR_MTLS_CERTS_PATH
      - SSL_CERTS_PATH=YOUR_SSL_CERTS_PATH
      - MONITOR_PATH=YOUR_MONITOR_PATH
      - OUTPUT_PATH=YOUR_OUTPUT_PATH
      - FRONTEND_PATH=YOUR_FRONTEND_PATH
      - WEB_SERVER_PORT=8000
      - WEB_SERVER_IP=0.0.0.0
      - LOG_DIR=/tmp
      - REQUEST_MONITORING_INTERVAL=20
      - JOB_MONITORING_INTERVAL=20
      - NODE_SYNC_INTERVAL=600
    ports:
      - "443:8000"
      - "55555:55555"
    tty: true
